[package]
name = "fuc_engine"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "Engine for the FUCing project."
repository.workspace = true
keywords = ["tools", "files"]
categories = ["filesystem"]
license.workspace = true

[dependencies]
crossbeam-channel = "0.5.6"
io-uring = "0.5.11"
libc = "0.2.139"
linux-raw-sys = "0.1.4"
thiserror = "1.0.38"
typed-builder = "0.11.0"

[target.'cfg(target_os = "linux")'.dependencies]
rustix = { version = "0.36.6", features = ["fs"] }

[target.'cfg(not(target_os = "linux"))'.dependencies]
rayon = "1.6.1"

[target.'cfg(not(any(target_os = "linux", target_os = "macos")))'.dependencies]
remove_dir_all = "0.7.0"

[dev-dependencies]
ftzz = "1.1.4"
rstest = "0.16.0"
supercilex-tests = "0.2.1"
tempfile = "3.3.0"
